name: Build and Deploy Angular App with Docker

on:
    push:
        branches: [deploy-develop-cepedi]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: Install dependencies
              run: npm install
            - name: Build Angular app
              run: npm run build
            - name: Login Deploy Hub
              run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build Docker image
              run: docker build -t mikaelle2rubia/frontend-grupo-brasileiro .
            - name: Push docker image
              run: docker push mikaelle2rubia/frontend-grupo-brasileiro

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Remove Docker Container
              run: docker rm -f grupobrafront
            - name: Run Docker container
              run: docker run -d -p 4200:4200 --name grupobrafront --network networksisbrasileiro mikaelle2rubia/frontend-grupo-brasileiro
